[build]
  base = "frontend"
  publish = "public"
  # command = "npm run build"  # 注释掉构建命令

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps --no-fund"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 