[build]
  base = "frontend"
  publish = "public"
  # command = "npm run build"  # 注释掉构建命令

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps --no-fund"
  NODE_OPTIONS = "--max_old_space_size=4096"

# 删除重定向规则，允许直接访问静态文件 